{% set name = "xwebrtc" %}
{% set version = "0.1.0" %}
{% set sha256 = "0c2d1e374836a3b92b097da2aec6f4253fceeff38b61aeff9680918b0d82e7c8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/QuantStack/xwebrtc/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py<35]
  features:   # [win]
    - vc14    # [win]

requirements:
  build:
    - toolchain
    - cmake
    - gcc-7             # [linux]
    - xeus >=0.13.0,<0.14
    - xtl >=0.4.0,<0.5
    - xproperty >=0.7.0,<0.8
    - xwidgets >=0.13.0,<0.14
    - clangdev          # [osx]
    - libcxx            # [osx]
  run:
    - xeus >=0.13.0,<0.14
    - cppzmq >=4.2.2,<4.3
    - xtl >=0.4.0,<0.5
    - xproperty >=0.7.0,<0.8
    - xwidgets >=0.13.0,<0.14

test:
  commands:
    - test -d ${PREFIX}/include/xwebrtc  # [unix]
    - test -f ${PREFIX}/include/xwebrtc/xchat.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/cmake/xwebrtc/xwebrtcConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\xwebrtc\xchat.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfig.cmake (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\xwebrtcConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://quantstack.net/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'C++ backend for the jupyter webrtc widget'
  dev_url: https://github.com/QuantStack/xwebrtc

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
